#!/usr/bin/env python3
# Copyright 2026 Sundar Ramesh Kumar.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTICE: This file is new in this fork and does not exist in the
# original google/meridian source.

"""Joins a Trivy OS report to measured load evidence and writes a triage table.

    python scripts/triage_container_os.py \
        --scan container-os-advisories.json \
        --probe docs/validation/container-reachability-2026-09-17.json \
        --output docs/validation/os-triage-2026-09-17.md

Why this exists. The container carries OS advisories that Debian has not fixed
and this fork therefore cannot fix. Publishing the raw count and stopping there
tells a reader nothing about whether any of it matters. Suppressing the count
would be worse. The middle path is to say, for every advisory, whether the
default analysis workflow loads any of the affected packages at all -- measured
by `scripts/container_reachability_probe.py`, not asserted.

The classification is deliberately crude and has exactly two values:

  `loaded`      at least one affected binary package was mapped into the
                analysis process during the probe.
  `not-loaded`  no affected package was mapped during the probe.

Neither value is a verdict. `loaded` does not mean exploitable: every Python
process maps libc. `not-loaded` does not mean unreachable: a user running
`docker run -it meridian bash` reaches far more than the probe did, and Debian
records advisories against a source package, so a row naming `libuuid1` may
describe a defect that actually lives in another binary built from the same
source. Those limits are printed into the generated document rather than left
for the reader to infer.

Exit code is 0 when the document is written, 1 on malformed input.
"""

from __future__ import annotations

import argparse
import collections
import datetime
import json
import pathlib
import sys
from collections.abc import Sequence

_SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]

_DEBIAN_TRACKER = "https://security-tracker.debian.org/tracker/"


def _load_json(path: pathlib.Path) -> dict:
  try:
    return json.loads(path.read_text(encoding="utf-8"))
  except (OSError, json.JSONDecodeError) as error:
    raise SystemExit(f"cannot read {path}: {error}") from error


def _advisories_from_scan(scan: dict) -> dict[str, dict]:
  """Collapses Trivy's per-package rows into one record per advisory id."""
  advisories: dict[str, dict] = {}
  for result in scan.get("Results") or []:
    for row in result.get("Vulnerabilities") or []:
      identifier = row.get("VulnerabilityID")
      if not identifier:
        continue
      record = advisories.setdefault(
          identifier,
          {
              "id": identifier,
              "severity": row.get("Severity", "UNKNOWN"),
              "packages": {},
              "title": row.get("Title", ""),
              "status": row.get("Status", ""),
          },
      )
      record["packages"][row.get("PkgName", "?")] = {
          "installed_version": row.get("InstalledVersion", ""),
          "fixed_version": row.get("FixedVersion") or None,
      }
  return advisories


def _classify(advisories: dict[str, dict], loaded: set[str]) -> None:
  for record in advisories.values():
    hits = sorted(set(record["packages"]) & loaded)
    record["loaded_packages"] = hits
    record["classification"] = "loaded" if hits else "not-loaded"


def _render(
    advisories: dict[str, dict],
    scan: dict,
    probe: dict,
    scan_path: pathlib.Path,
    probe_path: pathlib.Path,
    review_by: str,
) -> str:
  unfixed = {
      i: r
      for i, r in advisories.items()
      if all(p["fixed_version"] is None for p in r["packages"].values())
  }
  fixable = {i: r for i, r in advisories.items() if i not in unfixed}

  counts: collections.Counter = collections.Counter()
  for record in unfixed.values():
    counts[(record["severity"], record["classification"])] += 1

  os_info = scan.get("Metadata", {}).get("OS", {})
  today = datetime.date.today().isoformat()
  loaded = probe.get("loaded_os_packages", [])
  installed_count = probe.get("installed_package_count", 0)

  lines: list[str] = []
  add = lines.append

  add("<!-- NOTICE: This file is new in this fork and does not exist in the")
  add("     original google/meridian source. Generated by")
  add("     scripts/triage_container_os.py -- edit that script, not this file. -->")
  add("")
  add("# Container OS advisory triage")
  add("")
  add(f"Generated: {today}. Review by: **{review_by}**.")
  add("")
  add(
      f"Image OS: {os_info.get('Family', '?')} {os_info.get('Name', '?')}. "
      f"Scanned artifact: `{scan.get('ArtifactName', '?')}`."
  )
  add(
      f"Sources: scan `{scan_path.name}`, load evidence `{probe_path.name}` "
      f"(probe ran on {probe.get('platform', {}).get('machine', '?')}, "
      f"Python {probe.get('platform', {}).get('python', '?')}, "
      f"{probe.get('platform', {}).get('libc', '?')})."
  )
  add("")

  add("## What this document is")
  add("")
  add(
      "Every advisory below has no vendor fix in the scanner database used. "
      "Debian has not published a patched version, so this fork cannot patch "
      "it either. Rebuilding the image does not clear these; only the vendor "
      "shipping a fix does."
  )
  add("")
  add(
      "What this fork can do is say whether the default analysis workflow "
      "touches the affected packages at all. That is measured: "
      "`scripts/container_reachability_probe.py` imports Meridian, runs real "
      "tensor work and a report-module import inside the container, then reads "
      "`/proc/self/maps` and attributes every mapped file to its dpkg package."
  )
  add("")
  add(
      f"Measured result: **{installed_count} OS packages installed, "
      f"{len(loaded)} loaded** by that workflow."
  )
  add("")
  add("Loaded packages: " + ", ".join(f"`{p}`" for p in loaded) + ".")
  add("")

  add("## What it does not claim")
  add("")
  add(
      "- `loaded` is not a finding. Every Python process maps `libc6`. It means "
      "the package is in the process, nothing more."
  )
  add(
      "- `not-loaded` is not proof of unreachability. It describes the default "
      "command only. `docker run -it meridian bash`, a mounted volume, or any "
      "other entrypoint reaches more than the probe did."
  )
  add(
      "- Debian records an advisory against a **source** package and the "
      "scanner expands it across every binary package built from that source. "
      "A row naming `libuuid1` may describe a defect that lives in `mount` or "
      "`login`, which are built from the same `util-linux` source. Resolving "
      "which binary actually carries the defect requires the vendor tracker "
      "entry and is not determinable from scanner output."
  )
  add(
      "- No exploitability assessment has been performed on any entry here."
  )
  add("")

  add("## Summary")
  add("")
  add("| Severity | Affected package loaded | No affected package loaded | Total |")
  add("| --- | ---: | ---: | ---: |")
  total_loaded = total_not = 0
  for severity in _SEVERITY_ORDER:
    in_proc = counts[(severity, "loaded")]
    out_proc = counts[(severity, "not-loaded")]
    if not (in_proc or out_proc):
      continue
    total_loaded += in_proc
    total_not += out_proc
    add(f"| {severity} | {in_proc} | {out_proc} | {in_proc + out_proc} |")
  add(
      f"| **Total** | **{total_loaded}** | **{total_not}** | "
      f"**{total_loaded + total_not}** |"
  )
  add("")
  if fixable:
    add(
        f"{len(fixable)} advisories in this scan have a vendor fix available "
        "and are not triaged here; CI blocks high and critical findings in "
        "that group."
    )
  else:
    add(
        "No advisory in this scan has a vendor fix available. CI's gate on "
        "fixable high and critical findings is therefore not masking anything "
        "in this snapshot."
    )
  add("")

  for severity in _SEVERITY_ORDER:
    group = sorted(
        (r for r in unfixed.values() if r["severity"] == severity),
        key=lambda r: r["id"],
    )
    if not group:
      continue
    add(f"## {severity}")
    add("")
    add("| Advisory | Affected packages | Loaded | Vendor tracker |")
    add("| --- | --- | --- | --- |")
    for record in group:
      packages = ", ".join(f"`{p}`" for p in sorted(record["packages"]))
      if record["loaded_packages"]:
        loaded_cell = ", ".join(f"`{p}`" for p in record["loaded_packages"])
      else:
        loaded_cell = "none"
      tracker = f"[tracker]({_DEBIAN_TRACKER}{record['id']})"
      add(f"| `{record['id']}` | {packages} | {loaded_cell} | {tracker} |")
    add("")

  add("## Regenerating")
  add("")
  add("```")
  add("docker build --pull -t meridian:triage .")
  add("trivy image --scanners vuln --pkg-types os --ignorefile /dev/null \\")
  add("    --format json --output docs/validation/container-os-latest.json \\")
  add("    meridian:triage")
  add("# Copy the probe result out rather than writing through a mount: the")
  add("# container runs as uid 1000 and will not own your working tree.")
  add("docker run --name probe --entrypoint python meridian:triage \\")
  add("    scripts/container_reachability_probe.py --output /tmp/probe.json")
  add("docker cp probe:/tmp/probe.json \\")
  add("    docs/validation/container-reachability-latest.json")
  add("docker rm probe")
  add("python scripts/triage_container_os.py \\")
  add("    --scan docs/validation/container-os-latest.json \\")
  add("    --probe docs/validation/container-reachability-latest.json \\")
  add("    --output docs/validation/os-triage-latest.md")
  add("```")
  add("")
  add(
      "The scheduled `container-rescan` workflow runs this weekly and opens an "
      "issue when a new fixable high or critical finding appears."
  )
  add("")

  return "\n".join(lines) + "\n"


def _summary(
    advisories: dict[str, dict], scan: dict, probe: dict
) -> dict[str, object]:
  """Builds the compact record that is small enough to commit every week.

  A full Trivy report for this image is close to a megabyte. Committing one
  weekly would add tens of megabytes a year to a repository whose point is the
  source. The raw report stays a CI artifact; this keeps what a reader of the
  audit actually needs.
  """
  unfixed = sorted(
      (
          r
          for r in advisories.values()
          if all(p["fixed_version"] is None for p in r["packages"].values())
      ),
      key=lambda r: r["id"],
  )
  counts: collections.Counter = collections.Counter()
  for record in unfixed:
    counts[record["severity"]] += 1

  return {
      "date": datetime.date.today().isoformat(),
      "image_os": scan.get("Metadata", {}).get("OS", {}),
      "artifact": scan.get("ArtifactName", ""),
      "probe_platform": probe.get("platform", {}),
      "installed_package_count": probe.get("installed_package_count", 0),
      "loaded_os_packages": probe.get("loaded_os_packages", []),
      "advisories_total": len(advisories),
      "advisories_without_vendor_fix": len(unfixed),
      "advisories_with_vendor_fix": len(advisories) - len(unfixed),
      "unfixed_by_severity": dict(sorted(counts.items())),
      "unfixed_affecting_a_loaded_package": len(
          [r for r in unfixed if r["classification"] == "loaded"]
      ),
      "remaining_advisories": [
          {
              "id": r["id"],
              "severity": r["severity"],
              "classification": r["classification"],
              "loaded_packages": r["loaded_packages"],
              "packages": [
                  {"name": name, "installed_version": info["installed_version"]}
                  for name, info in sorted(r["packages"].items())
              ],
              "vendor_tracker": f"{_DEBIAN_TRACKER}{r['id']}",
          }
          for r in unfixed
      ],
      "limitations": [
          "No vendor fix exists for these in the scanner database used.",
          "`loaded` means a package was mapped into the analysis process; it "
          "is not an exploitability assessment.",
          "`not-loaded` describes the default container command only and does "
          "not prove unreachability.",
          "Debian records advisories against source packages; the scanner "
          "expands them across every binary package built from that source.",
      ],
  }


def main(argv: Sequence[str] | None = None) -> int:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--scan", type=pathlib.Path, required=True)
  parser.add_argument("--probe", type=pathlib.Path, required=True)
  parser.add_argument("--output", type=pathlib.Path, required=True)
  parser.add_argument(
      "--summary-output",
      type=pathlib.Path,
      default=None,
      help=(
          "Optional path for a compact JSON record of the findings, small "
          "enough to commit on every rescan."
      ),
  )
  parser.add_argument(
      "--review-in-days",
      type=int,
      default=90,
      help="Days until the triage should be re-read (default 90).",
  )
  args = parser.parse_args(argv)

  scan = _load_json(args.scan)
  probe = _load_json(args.probe)

  advisories = _advisories_from_scan(scan)
  if not advisories:
    print(f"no advisories found in {args.scan}", file=sys.stderr)

  loaded = set(probe.get("loaded_os_packages") or [])
  if not loaded:
    print(
        f"warning: {args.probe} lists no loaded packages; every advisory will "
        "be classified not-loaded",
        file=sys.stderr,
    )
  _classify(advisories, loaded)

  review_by = (
      datetime.date.today() + datetime.timedelta(days=args.review_in_days)
  ).isoformat()

  document = _render(
      advisories, scan, probe, args.scan, args.probe, review_by
  )
  args.output.parent.mkdir(parents=True, exist_ok=True)
  args.output.write_text(document, encoding="utf-8")

  if args.summary_output is not None:
    args.summary_output.parent.mkdir(parents=True, exist_ok=True)
    args.summary_output.write_text(
        json.dumps(_summary(advisories, scan, probe), indent=2, sort_keys=True)
        + "\n",
        encoding="utf-8",
    )

  unfixed = [
      r
      for r in advisories.values()
      if all(p["fixed_version"] is None for p in r["packages"].values())
  ]
  in_process = [r for r in unfixed if r["classification"] == "loaded"]
  print(f"advisories: {len(advisories)} ({len(unfixed)} without a vendor fix)")
  print(f"  affecting a loaded package: {len(in_process)}")
  print(f"  affecting no loaded package: {len(unfixed) - len(in_process)}")
  print(f"wrote {args.output} (review by {review_by})")
  return 0


if __name__ == "__main__":
  sys.exit(main())
